name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create env file
      run: |
        touch .env
        echo GOOGLE_API_KEY=$GOOGLE_API_KEY >> .env
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

    - name: Setup and install dependencies
      run: make setup

    - name: Make
      run: make
